# Configuration for Config Server itself
server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config
        default-label: main
  profiles:
    active: native

# Config Server specific settings
config:
  server:
    refresh:
      enabled: true
